// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `encode`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EngineManifest`, `Envelope`, `TimedEnvelope`

String engineManifestJson() =>
    RustLib.instance.api.crateApiEngineEngineManifestJson();

String catalogJson() => RustLib.instance.api.crateApiEngineCatalogJson();

String sourcesJson() => RustLib.instance.api.crateApiEngineSourcesJson();

String searchJson({required String query}) =>
    RustLib.instance.api.crateApiEngineSearchJson(query: query);

String positionsJson({required double dayFromJ2000}) => RustLib.instance.api
    .crateApiEnginePositionsJson(dayFromJ2000: dayFromJ2000);

String planRoutesJson({
  required String originId,
  required String destinationId,
  required double departureDayFromJ2000,
  required String vehicleId,
}) => RustLib.instance.api.crateApiEnginePlanRoutesJson(
  originId: originId,
  destinationId: destinationId,
  departureDayFromJ2000: departureDayFromJ2000,
  vehicleId: vehicleId,
);

String transferWindowJson({
  required String originId,
  required String destinationId,
  required double dayFromJ2000,
}) => RustLib.instance.api.crateApiEngineTransferWindowJson(
  originId: originId,
  destinationId: destinationId,
  dayFromJ2000: dayFromJ2000,
);
